### ISSUE TITLE
Library IDNA 2.7 and 2.8

### ISSUE THREAD

**Issue by homerjonathan** [requests/requests#4893] opened 2018-12-06 13:50 UTC
Summary.

Since off the grid I manually installed IDNA 2.8 as a dependant.  When installing requests via the .whl file v2.20.1 version.  It manually tried to download the IDNA 2.7 version.  I manually installed IDNA 2.7 and the install completed correctly.

What you expected.

To install correctly with IDNA 2.8

What happened instead.

When installing Requests version IDNA 2.7 will be downloaded.

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.1"
  },
  "platform": {
    "release": "2008ServerR2",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.20.1"
  },
  "system_ssl": {
    "version": "1010009f"
  },
  "urllib3": {
    "version": "1.24.1"
  },
  "using_pyopenssl": false
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment] 2018-12-06 14:01
Duplicate of #4890

**Comment by sigmavirus24** [comment] 2018-12-06 14:01
In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2018-12-06 14:01 UTC
