### ISSUE TITLE
POST request with 400 response throws ConnectionError

### ISSUE THREAD

**Issue by sebastianbauer** [requests/requests#4537] opened 2018-03-09 10:39 UTC
I make a POST request to an internal API. When some preconditions are not met the API responds with 400.

## Expected Result

Getting a response object with status_code == 400

## Actual Result

requests throws excpetion with ConnectionError

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.4"
  },
  "platform": {
    "release": "4.4.0-81-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "20000000"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by ghost** [comment] 2018-03-09 10:47
Additional information: This happens when the payload of the request was not received, yet. So it seems, requests can't handle this interruption.

**Comment by ghost** [comment] 2018-03-09 12:22
Even more information: Only happens when data parameter is a file object created with open.

**Comment by nateprewitt** [comment] 2018-03-09 15:05
@sebastianbauer there isn't enough information here to properly debug this. At a minimum we'll need the stacktrace so we can identify what kind of `ConnectionError` you're seeing, and preferably you'd also include a snippet of code to reproduce the issue.

Is this reproducible on more servers than your own? If not, this is likely a behavior in the interaction of your two code bases which is causing an issue. In that case, we'd prefer this was followed up on [StackOverflow](https://stackoverflow.com) which we have designated as a place for Requests questions/assistance inquiries. This issue tracker is specifically for reproducible defects in Requests. Thanks!

**Comment by ghost** [comment] 2018-03-09 15:25
@nateprewitt Thanks for your comment. I investigated further and it actually is not an issue with requests itself, but some underlying libs. It belongs to this one: https://bugs.python.org/issue25919

Sorry for the trouble.

**Comment by nateprewitt** [comment] 2018-03-09 15:43
No problem, thanks for checking back in! Closing since there's nothing left to address here.

**Closed by nateprewitt** 2018-03-09 15:43 UTC
