### ISSUE TITLE
Slow charset detection on Json file with no explicit encoding

### ISSUE THREAD

**Issue by gil9red** [requests/requests#4243] opened 2017-08-13 21:49 UTC
Hello!

In Reproduction Steps a large JSON file is downloaded - about 180MB

When I called rs.text (step 6), I did not wait for the result - I waited about 25 minutes

Console:

```
None
[1] total time: 4.0396250532594795 sec
[2] total time: 3.9574704779202534 sec
[3] total time: 0.271754903759728 sec
[4] total time: 4.078747523628547 sec
[5] total time: 0.27294884912872064 sec
[6] total time: 1515.3671759879826 sec
```

## Reproduction Steps

```python
class TimeThis(object):
    def __init__(self, title="TimeThis"):
        self.title = title
        self.start_time = None

    def __enter__(self):
        import time
        self.start_time = time.clock()

        return self

    def __exit__(self, exc_type, exc_value, exc_traceback):
        import time
        print('[{}] total time: {} sec'.format(self.title, time.clock() - self.start_time))


url = 'http://opendata.mkrf.ru/opendata/7705851331-register_movies/data-16-structure-3.json'

import requests
rs = requests.get(url)
print(rs.encoding)

with TimeThis("1"):
    rs.json()

with TimeThis("2"):
    import json
    json.loads(rs.content, encoding='utf-8')

with TimeThis("3"):
    rs.content.decode('utf-8')

with TimeThis("4"):
    import json
    json_data = rs.content.decode('utf-8')
    json.loads(json_data)

with TimeThis("5"):
    rs.encoding = 'utf-8'
    rs.text
    rs.encoding = None

with TimeThis("6"):
    rs.text

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.1"
  },
  "platform": {
    "release": "7",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.3"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

Windows7, Python 3.6.1 | Anaconda 4.4.0 (64-bit)

**Comment by Lukasa** [comment] 2017-08-14 05:40
Thanks for this! This is a dupe of #4235: closing to centralise.

**Closed by Lukasa** 2017-08-14 05:40 UTC
