### ISSUE TITLE
get an error OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF'),

### ISSUE THREAD

**Issue by liying1993** [requests/requests#4252] opened 2017-08-23 09:45 UTC
get an error OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF'),
## Expected Result
I just make a simple request, and i just  want to see what is the response 

## Actual Result

OpenSSL.SSL.SysCallError: (-1, 'Unexpected EOF')

## Reproduction Steps
here is my code

```python
import requests
r = requests.post("https://gateway.gopay.com.cn/Trans/WebClientAction.do", data=param_dict)
```

## System Information

    $ python -m requests.help

```
<paste here>
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by sigmavirus24** [comment] 2017-08-23 10:49
Hi @liying1993,

Please provide more information about your system. Without that we cannot provide much help.

**Comment by Lukasa** [comment] 2017-08-25 07:35
In the absence of more detail I'm assuming this is a dupe of #4244.

**Closed by Lukasa** 2017-08-25 07:35 UTC
Labels: Needs More Information

**Comment by liying1993** [comment] 2017-08-25 07:48
@Lukasa sorry,I have not check my email boxes in time,
I have asked our cooperative corporation which is the server I requested.They told me they need   to bound our company's.something about DNS.So,thank you
