### ISSUE TITLE
Default data should be dict, not list

### ISSUE THREAD

**Issue by kalaomer** [requests/requests#4574] opened 2018-04-05 12:17 UTC
https://github.com/requests/requests/blob/e4fc3539b43416f9e9ba6837d73b1b7392d4b242/requests/models.py#L223

In request class, empty data should be dict, not list.

**Comment by sigmavirus24** [comment] 2018-04-05 13:07
What makes you think that?

**Comment by nateprewitt** [comment] 2018-04-12 18:43
Since we haven’t had a response and the issue is unclear I’m going to close this for now. @kalaomer feel free to reopen this with more information if you feel there’s still an issue.

**Closed by nateprewitt** 2018-04-12 18:43 UTC
Labels: Propose Close
