### ISSUE TITLE
Error in request: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by w888** [requests/requests#4379] opened 2017-11-09 04:49 UTC
Summary.

## Expected Result

No exception

## Actual Result
```
INFO:root:Updating jobs in ['vm_docker_test.yaml'] ([])
Traceback (most recent call last):
  File "/usr/local/Cellar/jenkins-job-builder/1.6.2/libexec/bin/jenkins-jobs", line 10, in <module>
    sys.exit(main())
  File "/usr/local/Cellar/jenkins-job-builder/1.6.2/libexec/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 191, in main
    execute(options, config)
  File "/usr/local/Cellar/jenkins-job-builder/1.6.2/libexec/lib/python2.7/site-packages/jenkins_jobs/cmd.py", line 372, in execute
    n_workers=options.n_workers)
  File "/usr/local/Cellar/jenkins-job-builder/1.6.2/libexec/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 348, in update_jobs
    self.load_files(input_fn)
  File "/usr/local/Cellar/jenkins-job-builder/1.6.2/libexec/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 245, in load_files
    self.parser = YamlParser(self.global_config, self.plugins_list)
  File "/usr/local/Cellar/jenkins-job-builder/1.6.2/libexec/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 241, in plugins_list
    self._plugins_list = self.jenkins.get_plugins_info()
  File "/usr/local/Cellar/jenkins-job-builder/1.6.2/libexec/lib/python2.7/site-packages/jenkins_jobs/builder.py", line 205, in get_plugins_info
    raise e
jenkins.JenkinsException: Error in request: EOF occurred in violation of protocol (_ssl.c:590)
```

## Reproduction Steps

i am trying to create a jenkins jobs through jjb

```
jenkins-jobs --conf ./jenkins_jobs.ini update vm_docker_test.yaml
```

where jenkins_jobs.ini

```
[job_builder]
ignore_cache=True
keep_descriptions=False
recursive=False
exclude=.*:manual:./development
allow_duplicates=False
allow_empty_variables=True

[jenkins]
user=someuser
password=somepassword
url=https://subdomain.company.com/jenkins/group
query_plugins_info=True
```

## System Information

```
openssl version
OpenSSL 1.0.2l  25 May 2017

pip freeze
asn1crypto==0.23.0
certifi==2017.7.27.1
cffi==1.11.2
chardet==3.0.4
cryptography==2.1.2
Cython==0.27.1
enum34==1.1.6
http-client==0.1.22
idna==2.5
ipaddress==1.0.18
ndg-httpsclient==0.4.3
pyasn1==0.3.7
pycparser==2.18
pycurl==7.43.0
pyOpenSSL==17.3.0
requests==2.18.4
six==1.11.0
urllib3==1.22
```

**Comment by Lukasa** [comment] 2017-11-10 21:53
It seems like your Jenkins doesn't like our TLS handshake. Can you run `openssl s_client -connect jenkins_host:jenkins_port` and provide the output here?

**Comment by sigmavirus24** [comment] 2017-11-28 13:14
Hi @w888,

It seems this isn't an issue for you any longer. If I'm wrong, please provide us with the information that @Lukasa requested.

Until we have that information, I'm closing this issue because it does not have enough information for us to act on it.

Cheers,
Ian

**Closed by sigmavirus24** 2017-11-28 13:14 UTC

**Comment by saurabhpilot** [comment] 2017-12-06 20:18
I am hit the same error. sending some REST API call via requests

>>> r = requests.post(url=url,headers=headers,data=json.dumps(Data),verify=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='172.16.76.172', port=443): Max retries exceeded with url: /tssm/onboard-tenant (Caused by SSLError(SSLEOFError(8, u'EOF occurred in violation of protocol (_ssl.c:590)'),))

$ openssl version
OpenSSL 1.0.2m  2 Nov 2017
$ python --version
Python 2.7.10
