### ISSUE TITLE
Url with vertical bar

### ISSUE THREAD

**Issue by jerbluba** [requests/requests#4565] opened 2018-03-29 15:34 UTC
I found if we have "|" vertical bar in url will show

Expecting value: line 9 column 1 (char 16)

The following is my code...

req = requests.session()
req.get('http://mis.twse.com.tw/stock/index.jsp',headers={'Accept-Language': 'zh-TW'})   
response = req.get(self.query_url)
print(content)

self.query_url is aurl have "|" 

For example:

http://mis.twse.com.tw/stock/api/getStockInfo.jsp?_=1522229112409&json=1&delay=0&ex_ch=tse_3374.tw|tse_2455.tw|tse_8086.tw|tse_3105.tw|tse_4991.tw|tse_2360.tw|tse_4971.tw|tse_6271.tw|tse_2448.tw|tse_2454.tw|tse_3443.tw|tse_3661.tw|tse_3035.tw|tse_2376.tw|tse_2377.tw

## Expected Result

I hope I can read url with "vertical bar" 

## Actual Result

Expecting value: line 9 column 1 (char 16)

## Reproduction Steps

```python
import requests

```

## System Information

version python3.6

**Comment by sigmavirus24** [comment] 2018-03-29 15:40
I cannot reproduce this locally on Python 3.6 with 

```json
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.3"
  },
  "platform": {
    "release": "17.4.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020ef"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

There isn't enough detail to help and I'm closing this. If you need help with code, please visit [StackOverflow](https://stackoverflow.com) as our issue tracker is only for bugs.

**Closed by sigmavirus24** 2018-03-29 15:40 UTC

**Comment by jerbluba** [comment] 2018-03-29 15:45
I am sorry I modify the Reproduction Steps...  
Can you reproduce this again, please?

**Comment by sigmavirus24** [comment] 2018-03-29 15:49
@jerbluba with those refined, this firmly falls into Not a Bug territory. The JSON module (not provided by Requests) cannot decode something that isn't JSON, thus you need to handle that body separately. StackOverflow is the right place for this discussion.

**Comment by jerbluba** [comment] 2018-03-29 16:44
But I observe it by Wireshark，the "vertical bar" become "%7C" ，so I can't get json data from the url.

Please help me.

![vertical_bar](https://user-images.githubusercontent.com/6846724/38101517-150fe228-33b3-11e8-98e0-c6158ccc397e.PNG)
