### ISSUE TITLE
http redirect to non http causes exception

### ISSUE THREAD

**Issue by philborman** [requests/requests#4539] opened 2018-03-10 18:55 UTC
Summary.
If a http page redirects via 301 to a non-http location, eg a magnet link, requests raises exception and the redirect link is not available except in the error text
## Expected Result
Would be better if it returned status_code=301 and content=redirect link
## Actual Result
exception No connection adapters were found for 'magnet:?xt=urn:btih...

**Comment by nateprewitt** [comment] 2018-03-10 20:16
Hi @philborman, thanks for reporting this. This is actually a duplicate of #4362, which I think @kennethreitz's needs to take a look at. The `request.next` feature broke handling custom schemes, so until that's resolved, Requests 2.16+ isn't able to handle non-http style URI redirects.

**Closed by nateprewitt** 2018-03-10 20:16 UTC

**Comment by philborman** [comment] 2018-03-10 20:32
Not quite, I haven't disabled redirects like #4362   I want the redirect to be followed providing its the same type (http redirects to http)  but if it's a different schema or an invalid schema return the status code and content so it can be handled by the calling app.

My use case:
Downloading a torrent or magnet
If the torrent (http) is moved to a new location (http), requests redirect will handle it
If the torrent redirects to a magnet link, don't throw an exception, return the 301 status and provide the new location in the response content so my app can decide what to do.

**Comment by nateprewitt** [comment] 2018-03-10 20:47
@philborman that's something that is easily implemented with a small redirect function when our default behaviour is disabled. That's the reason we added the `allow_redirects` functionality initially. Until that's fixed, I don't know if we can do a lot here.

**Comment by philborman** [comment] 2018-03-10 20:53
Maybe I am getting it wrong then. I tried with allow_redirects set to False and got a 301 status_code but the contents was empty so no way of knowing where the redirect pointed to. I could only get that by allowing redirects to cause the exception  and then scanning the error text for the new location. Messy, but it works.  Thanls for your quick response.

**Comment by kennethreitz** [comment] 2018-03-10 20:57
@philborman you get the location of the redirect from the 'Location' header, not the body
