### ISSUE TITLE
Multipart PUT?

### ISSUE THREAD

**Issue by aparamon** [requests/requests#4660] opened 2018-05-26 06:05 UTC
Does `requests` currently support Multipart-encoded files in `PUT` requests?

It seems that both
http://docs.python-requests.org/en/master/user/quickstart/#post-a-multipart-encoded-file
and
https://toolbelt.readthedocs.io/en/latest/uploading-data.html
only work with `POST`. For `PUT` requests, I keep getting error "413 Request Entity Too Large" from my Apache httpd.

Should that be considered a bug, improvement suggestion, or there is some fundamental limitation why `PUT` shouldn't upload large files? (yes, my `GET` would stream the huge file unmodified)

Original StackOverflow question:
https://stackoverflow.com/questions/50533901/multipart-put-with-requests

**Comment by sigmavirus24** [comment] 2018-05-26 11:38
> I keep getting error "413 Request Entity Too Large" from my Apache httpd.

The documentation might be misleading, but we do support `multipart/form-data` content in a `PUT`. `POST` requests are merely the 99% use-case. It seems your Apache server, however, will not accept the request you're sending for literally the reason it is telling you.

The only potential "bug" with requests might be that your Apache server is expecting us to use the `100-continue` workflow which we cannot support. There are other issues about this and so this is at best a duplicate of those.

Any further information should continue to be added on StackOverflow.

**Closed by sigmavirus24** 2018-05-26 11:38 UTC
