### ISSUE TITLE
.. is not interpreted correctly with redirections

### ISSUE THREAD

**Issue by hydrargyrum** [requests/requests#4622] opened 2018-05-02 21:43 UTC
When a site redirects to an URL containing "/../", requests passes it verbatim instead of interpreting it.

## Expected Result

requests should remove the ".." component and the previous component, by interpreting the ".." as meaning "parent folder".
All real browsers do it. libcurl/curl (and wget) does it too.
Test for example https://httpbin.org/redirect-to?url=https%3A%2F%2Fhttpbin.org%2Ffoo%2F%2E%2E%2Fget

## Actual Result

requests fails to interpret it like other HTTP clients do and passes the "/../" verbatim, leading to errors on servers, ranging from 500 errors to 404 errors (as for httpbin).

## Reproduction Steps

```python
import requests
r = requests.get('https://httpbin.org/redirect-to?url=https%3A%2F%2Fhttpbin.org%2Ffoo%2F%2E%2E%2Fget')
print(r.status_code, r.url)
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": ""
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.15"
  }, 
  "platform": {
    "release": "4.15.0-1-amd64", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "", 
    "version": null
  }, 
  "requests": {
    "version": "2.18.4"
  }, 
  "system_ssl": {
    "version": "1010008f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment] 2018-05-02 23:08
Hi @hydrargyrum, thanks for taking the time to bring this to our attention. This is actually a known issue and duplicate of #2982. We can’t currently resolve it in the Requests 2.x branch for backwards compatibility reasons. We have a todo for Requests 3.0 to resolve it, either by moving to the rfc3986 library for url parsing, or finding another alternative. For consolidation purposes I’m closing this in favor of the original ticket.

**Closed by nateprewitt** 2018-05-02 23:08 UTC
