### ISSUE TITLE
proxies in session not taken into account

### ISSUE THREAD

**Issue by navidof** [requests/requests#4599] opened 2018-04-19 14:59 UTC
When creating a session object, and setting proxies information, the proxy information is not used in subsequent requests:

SESS = requests.Session()
SESS.auth = (USER, PWD)
SESS.verify = False
SESS.proxies = {'https': None}

## Expected Result

SESS.get(URL + '/' + ENDPOINT)

should bypass the proxy and be able to resolve the internal URL.

## Actual Result

502: notresolvable for url

But passing the same proxy information to the get works:
SESS.get(URL + '/' + ENDPOINT, proxies={'https': None})

works as expected

## Reproduction Steps

```python
import requests
SESS = requests.Session()
SESS.auth = (USER, PWD)
SESS.verify = False
SESS.proxies = {'https': None}

```

## System Information

requests 2.13.0
python 3.5.2
Fedora 20

**Comment by nateprewitt** [comment] 2018-04-19 15:21
Hi @navidof, before we dig too far into this, can you confirm this is still an issue in 2.18.4 with urllib3 1.22?

Requests 2.13 is fairly old now and there’s been some proxy work done since then.

**Comment by nateprewitt** [comment] 2018-05-20 19:16
Hey again @navidof, I'm unable to reproduce this with 2.18.4 and since this hasn't seen an update in the last month, I'm going to close it out.

**Closed by nateprewitt** 2018-05-20 19:16 UTC
Labels: Needs More Information

**Comment by navidof** [comment] 2018-05-21 08:35
Hi Nate,

Thanks for your time, I didn't know how to test with another request package, anyway it's not possible for my use case to use another version.
The workaround is simple, so no worries if it's not fixed in my version.

Regards,
Navid

----- Mail original -----
De: "Nate Prewitt" <notifications@github.com>
À: "requests/requests" <requests@noreply.github.com>
Cc: "navidof" <navidof@free.fr>, "Mention" <mention@noreply.github.com>
Envoyé: Dimanche 20 Mai 2018 21:17:00
Objet: Re: [requests/requests] proxies in session not taken into account (#4599)



Hey again @navidof , I'm unable to reproduce this with 2.18.4 and since this hasn't seen an update in the last month, I'm going to close it out.
