### ISSUE TITLE
AttribueError at iter_content

### ISSUE THREAD

**Issue by andreyshokkhin** [requests/requests#4614] opened 2018-04-26 18:40 UTC
I don't know who to blame (requests or urllib3), but though you guys can be interested:
```
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('http://imodules.com/')
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): imodules.com
DEBUG:urllib3.connectionpool:http://imodules.com:80 "GET / HTTP/1.1" 301 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.imodules.com
DEBUG:urllib3.connectionpool:http://www.imodules.com:80 "GET / HTTP/1.1" 302 None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/sessions.py", line 658, in send
    r.content
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/urllib3/response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/urllib3/response.py", line 598, in read_chunked
    self._update_chunk_length()
  File "/Users/ashokhin/.venv/adstxt/lib/python3.6/site-packages/urllib3/response.py", line 540, in _update_chunk_length
    line = self._fp.fp.readline()
AttributeError: 'NoneType' object has no attribute 'readline'

```
    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.4"
  },
  "platform": {
    "release": "17.5.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020df"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by colinfike** [comment] 2018-04-29 00:42
This issue is occurring when the redirects are being followed. Entering `https://www.imodules.com` works fine.

**Comment by nateprewitt** [comment] 2018-04-29 00:48
@colinfike, this occurs when the underlying connection in urllib3 has been closed but the Request objects content field hasn’t been populated correctly.

You can find a couple similar issues that were closed due to IDEs or mocking frameworks modifying the object inappropriately. If you’re seeing this around redirects, my gut feeling is this may be related to the `.next` attribute which was added in a recent version. It’s had a few other issues logged against it that haven’t been examined enough yet.

**Comment by colinfike** [comment] 2018-04-30 22:23
OK, I'll take a look and see if anything shakes out

**Comment by colinfike** [comment] 2018-05-01 03:53
So I investigated this a bit more and while I haven't found the root cause as to why this is happening in requests, urllib3 seems to have been updated recently to fix this bug.

Seems to be this commit https://github.com/urllib3/urllib3/commit/997280928daf6e440511baf75d60d25d0813d88a#diff-01955f24bc4d0d621454698a584ab854 that fixes the issue.

**Comment by nateprewitt** [comment] 2018-05-05 23:40
@colinfike, yep, that looks right. I ran a quick test with the master branch of urllib3 and the issue is resolved. This should be addressed in the next minor release of Requests following a urllib3 release. Closing since the issue is resolved. Thanks everyone!

**Closed by nateprewitt** 2018-05-05 23:40 UTC
Labels: Needs More Information
