### ISSUE TITLE
possible memory leak 

### ISSUE THREAD

**Issue by tarjintor** [requests/requests#4916] opened 2018-12-24 06:07 UTC
It seems that my code memory used is increase slowly,I find that even the simplest code will lead this.

## Expected Result
memory won't slowly increase
## Actual Result
memory is slowly increase, running after one hour
![_15456276853678](https://user-images.githubusercontent.com/12421352/50391984-2c7dd680-0785-11e9-9d68-f69823654145.png)
![_15456315045182](https://user-images.githubusercontent.com/12421352/50391986-2e479a00-0785-11e9-8c3d-a6f2792ec8a4.png)

## Reproduction Steps

```python
import requests
def f():
    while 1:
        s = requests.get('https://www.baidu.com')
        text = s.text

if __name__ == '__main__':
    f()
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.3.1"
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.6"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010009f",
    "version": "18.0.0"
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "100020ff"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": true
}

```

**Comment by tirkarthi** [comment] 2019-01-30 06:30
Seems to be a similar issue : https://github.com/requests/requests/issues/4934

**Comment by sigmavirus24** [comment] 2019-02-04 11:55
Duplicate of #4934

**Closed by sigmavirus24** 2019-02-04 11:55 UTC
