### ISSUE TITLE
SSLError has been changed to ConnectionError in requests 2.18.2?

### ISSUE THREAD

**Issue by 5j9** [requests/requests#4211] opened 2017-07-30 12:33 UTC
In  requests-2.18.1 and earlier:

`requests.get('https://testssl-expire-r2i2.disig.sk/index.en.html')`

Used to raise `SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)`

But as of requests-2.18.2 (the latest version), the same URL is returning `ConnectionError: HTTPSConnectionPool(host='testssl-expire-r2i2.disig.sk', port=443): Max retries exceeded with url: /index.en.html (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))`

I just need a confirmation that this change is intentional and if it is going to remain so (or not).

Thanks.

**Comment by Lukasa** [comment] 2017-07-30 12:45
Thanks for this! This is a duplicate of #4902, so I'll refer you to that issue.

**Comment by Lukasa** [comment] 2017-07-30 12:46
Sorry, I meant #4209.

**Closed by Lukasa** 2017-07-30 12:45 UTC
