### ISSUE TITLE
POST changed to GET when request got HTTP/3xx

### ISSUE THREAD

**Issue by airween** [requests/requests#4515] opened 2018-02-15 10:48 UTC
A POST request changed to GET request when  the Request object got 3xx answer from server.

I don't know the RFC exactly, but the expected result would be that request repeat as POST at new URL.

Here is the code:
```
r = requests.post("http://foobar.com/script", data={'foo': 'bar'})
```

The server answer:

```
HTTP/1.1 302 Found
Date: Thu, 15 Feb 2018 10:42:16 GMT
Server: Apache/2.4.25 (Debian)
Location: https://foobar.com/script
Content-Length: 222
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
```

Then Request repeats the request as GET.

Debian Linux 9.3
Python3 (3.5.3)
Apache2.4 (the server where Request sends the request)

```
>>> requests.__version__
'2.12.4'
```
I've changed the url to https schema, then it works.

**Comment by sigmavirus24** [comment] 2018-02-15 14:09
In the future, please search **closed and** open issues before creating new ones that are duplicates. 

Duplicate of #4251 
Duplicate of #4236 
Duplicate of #3915 

This behaviour protects you against Requests sending sensitive data to the wrong server, see also

- [CVE 2014-1829](http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2014-1829)
- [CVE 2014-1830](http://www.cve.mitre.org/cgi-bin/cvename.cgi?name=2014-1830)

**Closed by sigmavirus24** 2018-02-15 14:09 UTC

**Comment by airween** [comment] 2018-02-15 14:22
@sigmavirus24 - thanks for feedback.

Sorry, next time I'll check the closed issues too.

Regards,
a.

**Comment by amustapha** [comment] 2018-03-11 07:57
In my own case, I reconfigured the server redirect using 307 instead of 301/302. This makes sure that request body and type is not tampered.

**Comment by airween** [comment] 2018-03-11 08:04
@m-bryo, thanks, I'll check out.
