### ISSUE TITLE
urllib3.exceptions.NewConnectionError

### ISSUE THREAD

**Issue by pinkynrg** [requests/requests#4744] opened 2018-07-20 17:20 UTC
It seems like I'm getting an Exception from urllib3: urllib3.exceptions.NewConnectionError.

## Expected Result
I am expecting to catch the exception using requests.exceptions.RequestException

## Actual Result
The exception in not getting caught. 

## Reproduction Steps

```python
import requests

try:
  response = requests.post('http://0.0.0.0:8080', data = {'token': 'some_token'})
  if response.status_code == 200:
    data = json.loads(response.text)
    if ('user' in data):
      user = User.objects.get(username=data['user']['username'])
except requests.exceptions.RequestException as e:
  result = {"error": e}
```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.4"
  },
  "platform": {
    "release": "17.5.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "100020ef"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}
```

**Comment by nateprewitt** [comment] 2018-07-20 19:53
Hi @pinkynrg, can we please get the full stack trace you’re seeing and a minimum viable reproduction?

A simplified version of what you’ve supplied returns a `requests.exception.ConnectionError` which wraps the `NewConnectionError`.

```python
import requests

requests.post(‘http://0.0.0.0:8080’, data={‘test’: ‘data’})
```

**Comment by sigmavirus24** [comment] 2018-08-04 12:29
Closing due to lack of information or ability to reproduce.

**Closed by sigmavirus24** 2018-08-04 12:29 UTC
Labels: Needs More Information
