### ISSUE TITLE
Requests and Let's Encrypt Certificates

### ISSUE THREAD

**Issue by MonsterDeveloper** [requests/requests#3935] opened 2017-03-22 17:04 UTC
While using Requests, I noticed strange thing: Requests doesn't accept Let's Encrypt Certificates. Only with `verify=False` library doesn't raise an exception (tested on my https Tornado server). Maybe add Let's Encrypt Authority X3 to Requests' CA?

**Comment by kennethreitz** [comment] 2017-03-22 17:18
works fine for me!

**Comment by kennethreitz** [comment] 2017-03-22 17:18
tested against httpbin.org

**Comment by MonsterDeveloper** [comment] 2017-03-23 06:49
Httpbin use lets encrypt?

**Comment by MonsterDeveloper** [comment] 2017-03-23 06:50
I have issue like https://github.com/kennethreitz/requests/issues/2955

**Comment by Lukasa** [comment] 2017-03-23 08:29
@MonsterDeveloper If you have an issue like #2955, have you tried examining the solution provided there? Can you tell me what server you're having trouble with? Can you tell us what version of Python and OpenSSL you're using? The reason is that Requests *does* trust LE certificates.

**Comment by sigmavirus24** [comment] 2017-03-23 11:37
@MonsterDeveloper I also cannot reproduce this, but there's also too many versions of Python, OpenSSL, and Requests to try to guess at your current problematic configuration. Please supply as much information as possible.

**Comment by MonsterDeveloper** [comment] 2017-03-23 12:17
Python: 3.5
Requests: latest!
PyOPENSSL: latest
OpenSSL: latest
OS: Ubuntu 16.04

**Comment by Lukasa** [comment] 2017-03-23 12:18
And what URL?

**Comment by Lukasa** [comment] 2017-03-23 12:18
Also...can you tell us what you mean by latest? There are different values of latest depending on where you're getting those packages from.

**Comment by MonsterDeveloper** [comment] 2017-03-23 12:19
I got these packages from PyPi

**Comment by Lukasa** [comment] 2017-03-23 12:20
You definitely didn't get OpenSSL from PyPI. So can you please provide the actual version numbers in all of those cases?

**Comment by jsha** [comment] 2017-05-04 20:49
@MonsterDeveloper it would also be helpful to say what site you are trying to access. One of the most common problems is that a site is misconfigured and doesn't serve its intermediate certificate (as described in #2955).

**Comment by sigmavirus24** [comment] 2017-07-29 23:37
There's been very little detail provided to help us debug this issue. Since the discussion stopped months ago, I'm closing this. We can reopen if necessary.

**Closed by sigmavirus24** 2017-07-29 23:37 UTC
