### ISSUE TITLE
Docs: Requests 3 info link at top of main page points to a 404

### ISSUE THREAD

**Issue by joshstaiger** [requests/requests#4767] opened 2018-08-14 17:32 UTC
The link that states "Requests 3.0 development is underway, and your financial help is appreciated!"
at the top of every doc page (eg: http://docs.python-requests.org/en/master/), currently points to the url:

https://www.kennethreitz.org/requests3

Which, at the time of writing is a "404 not found" page.

I'd like to learn about requests 3, so this should point somewhere useful :) (or be removed temporarily)

**Comment by pauricthelodger** [comment] 2018-08-14 19:07
Just noticed the same. Looks like it's been down a while according to Internet Archive but https://web.archive.org/web/20180701201816/https://www.kennethreitz.org/requests3 should work for the moment, @joshstaiger =)

**Comment by sigmavirus24** [comment] 2018-08-15 13:33
Duplicate of https://github.com/requests/requests/issues/4743

In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2018-08-15 13:33 UTC
