### ISSUE TITLE
Connection aborted , while uploading files over 10GB

### ISSUE THREAD

**Issue by kpputhiyattil** [requests/requests#4480] opened 2018-01-19 05:39 UTC
Summary.
When I try to upload a file more than 5GB, connection error occurs, saying the connection is aborted.
ProtocolError('Connection aborted.', error("(-1, 'Unexpected EOF')",))

## Expected Result
Large File should be uploaded

## Actual Result
Exception occurs
ProtocolError('Connection aborted.', error("(-1, 'Unexpected EOF')",))
What happened instead.

## Reproduction Steps

```python
             import requests
             payload={obj.backupId:backupId,obj.folderId:folderId,obj.backupTxnId:backupTxnId,obj.fileHash:fileHash,obj.accessed:accessed,obj.created:created,obj.modified:modified,obj.isDirectUpload:isDirectUpload,obj.fileName:fileName,obj.fileSize:fileSize, obj.contentHash:contentHash}
            urls=obj.upload_url
             e = encoder.MultipartEncoder(fields={'backupfile':(os.path.basename(backupfile.encode('unicode-escape')),open(r"D:\\Movies\\Aruvi\\5GB.mp4","rb") )})
            m = encoder.MultipartEncoderMonitor(e)
            m._read = m.read
            m.read = lambda size: m._read(1024)
            headers = {'Accept': 'application/json, text/javascript, */*; q=0.01',
                            'Accept-Encoding': 'gzip, deflate, br',
                            'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6','Connection': 'keep-alive','Content-Type': m.content_type}
            uploadObj = BackupResponse.upload_files()
            response = APIResponse.Response(uploadObj)
        
           resp_obj = requests.post(urls, params=payload, data=m, files=None, headers=headers, cookies=self.cookies)
            response_object = calling_obj.set_attr(resp_obj.json())
```

## System Information

```
    {
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.0.3"
  },
  "idna": {
    "version": ""
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.14"
  },
  "platform": {
    "release": "10",
    "system": "Windows"
  },
  "pyOpenSSL": {
    "openssl_version": "1010006f",
    "version": "17.2.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "100020bf"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment] 2018-01-19 05:47
Hey @kpputhiyattil, I'm going to have to ask you to please stop opening the same issue repeatedly. As we've stated in the previous issues, this is not a defect in Requests, the server is closing the connection on you. Please use [StackOverflow](https://stackoverflow.com) for further usability questions. Thank you!

**Closed by nateprewitt** 2018-01-19 05:47 UTC

**Comment by kpputhiyattil** [comment] 2018-01-19 05:50
If you are closing the issue without addressing the concern what can I do?
I am using your library to upload the file and your library is not allowing
it. so its your responsibility to address the issue and to fix it

**Comment by kpputhiyattil** [comment] 2018-01-19 05:52
Instead of closing the issue, it's your ultimate responsibility to resolve
the issue facing by us.

**Comment by nateprewitt** [comment] 2018-01-19 06:05
@kpputhiyattil, we've provided clear instructions on how to get your request for help addressed. We're trying to reduce unnecessary spam to an issue list monitored by 1200 people who want to stay up to date on *defects* in Requests.

As for responsibility, Requests is freely provided software maintained for free by volunteers. It's clearly stated in the license that Requests is provided "as is" with no guarantee of support. If you choose to use Requests, you are choosing to accept those conditions. This is all mostly irrelevant though, as I stated above, because the server you're talking to is choosing to close the connection and we have no control over that.

If you need further help, please file an issue on [StackOverflow](https://stackoverflow.com).

**Comment by sigmavirus24** [comment] 2018-01-19 15:05
@kpputhiyattil Given the spamming of issues here and the consistent disregard for our clear and respectful communications, I've blocked you from participating on this repository and other repositories in the requests organization for a short while.

For help determining the issue you're encountering, you must use [StackOverflow](https://stackoverflow.com). And for the last time, this is not a bug in Requests.
