### ISSUE TITLE
help.py get a error  when i run it alone

### ISSUE THREAD

**Issue by songyingxin** [requests/requests#4732] opened 2018-07-11 02:20 UTC
Summary.

## Expected Result
```
{
  "chardet":{
    "version":"3.0.4"
  },
  "cryptography":{
    "version":"2.1.4"
  },
  "idna":{
    "version":"2.6"
  },
  "implementation":{
    "name":"CPython",
    "version":"3.6.4"
  },
  "platform":{
    "release":"4.15.0-24-generic",
    "system":"Linux"
  },
  "pyOpenSSL":{
    "openssl_version":"100020df",
    "version":"17.5.0"
  },
  "requests":{
    "version":{

    }
  },
  "system_ssl":{
    "version":"100020ff"
  },
  "urllib3":{
    "version":"1.22"
  },
  "using_pyopenssl":true
}
```
## Actual Result

```
Traceback (most recent call last):
  File "/home/songyingxin/Code/Github/requests/requests/help.py", line 119, in <module>
    main()
  File "/home/songyingxin/Code/Github/requests/requests/help.py", line 115, in main
    print(json.dumps(info(), sort_keys=True, indent=2))
  File "/home/songyingxin/anaconda3/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/songyingxin/anaconda3/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/home/songyingxin/anaconda3/lib/python3.6/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/home/songyingxin/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/songyingxin/anaconda3/lib/python3.6/json/encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "/home/songyingxin/anaconda3/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/home/songyingxin/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'module' is not JSON serializable
```

## Reproduction Steps
the error is because the json , when i change it as `import ujson as json` , everything is ok. I think there maybe some bug in different platform .  my OS is 'Linux' ,  'Ubuntu16.04", python-version: "Cpython", "3.6.4".

**Comment by nateprewitt** [comment] 2018-07-11 02:24
Hi @songyingxin, it looks like you may have a file named requests.py in your project that is hijacking the namespace we’re expecting. Alternatively, you may have two different versions of requests installed, one of which is older and doesn’t support help.

**Comment by sigmavirus24** [comment] 2018-07-12 13:37
Also, what does "run it alone" mean?

**Comment by sigmavirus24** [comment] 2018-08-04 12:30
No information provided for reproduction. Closing.

**Closed by sigmavirus24** 2018-08-04 12:30 UTC
Labels: Needs More Information, Propose Close
