### ISSUE TITLE
SSLError(SSLError(0, 'unknown error (_ssl.c:3517)

### ISSUE THREAD

**Issue by JeetBhattachariya** [requests/requests#4873] opened 2018-11-13 22:54 UTC
I am trying to invoke a api which is sitting in a load balancer server. The server uses certificate chain which i downloaded from browser in .p7b file and passing in my code 
`r=request.get(uri,headers=header,verify='certificate.p7b').`
 Even I tried generating .pem file through openssl commands, but it didn't work. I also tried using "verify=False" sttement. But getting the same error:
Please help.

**Comment by nateprewitt** [comment] 2018-12-31 00:00
Hi @JeetBhattachariya, this is an exception in _ssl.c on line 3517. That's code within CPython, so without an exact version of your interpreter and likely a dummy cert that we can reproduce this with, it's going to be very difficult to debug.

We can take a closer look if you can provide all of the information you originally requested, but this appears to be a cert or standard library issue. [StackOverflow](https://www.stackoverflow.com) is probably a better venue for that though since this doesn't appear to be an issue with Requests code base. I'm going to close this for now, but feel free to add a link to the StackOverflow question if you choose to create one.

**Closed by nateprewitt** 2018-12-31 00:00 UTC
