### ISSUE TITLE
Making a request with multipart/form-data (file=) should throw an error if the barrier defined in the headers does not match

### ISSUE THREAD

**Issue by SM-Wistful** [requests/requests#4589] opened 2018-04-14 23:29 UTC
I am unable to make a pull request at this time, but I think this should be added. The server will not understand the request if the content-type header's barrier= is not the same as the one generated by requests. At the very least there should be a warning.

**Comment by sigmavirus24** [comment] 2018-04-15 12:46
Please provide us with the output of

```
python -m requests.help
```

If that is unavailable on your version of Requests please provide some basic information about your system (Python version, operating system, etc).

Additionally, this appears to be a duplicate of several issues. In the future, please search **closed and** open issues before creating new ones that are duplicates.

**Closed by sigmavirus24** 2018-04-15 12:46 UTC
