### ISSUE TITLE
`Collections.Callable` DeprecationWarning

### ISSUE THREAD

**Issue by hsolbrig** [requests/requests#4594] opened 2018-04-17 22:23 UTC
Summary.
Python 3.7.0b3 has a new warning:
```text
.../python3.7/site-packages/requests/models.py:177: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if isinstance(hook, collections.Callable):
```

## Expected Result
Need to change this line (and other references) to `if isinstance(hook, collections.abc.Callable):`

What you expected.

## Actual Result

What happened instead.

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": ""
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.0b3"
  },
  "platform": {
    "release": "16.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "",
    "version": null
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1010007f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": false
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment] 2018-04-17 22:26
Hey @hsolbrig, this is actually a duplicate of #4494 and we have a PR in the queue to address this. Next time please make sure to check issues and pull requests before opening a new one. Thanks for taking the time to bring this to our attention though!

**Closed by nateprewitt** 2018-04-17 22:26 UTC
