### ISSUE TITLE
Possible Memory Leak 

### ISSUE THREAD

**Issue by le1nux** [requests/requests#4191] opened 2017-07-12 15:32 UTC
I'm crawling a lot of different URLs using the requests library and I encountered that the process takes more and more RAM over time. 
Basically all I do is calling this iteratively from multiple threads:
```{python}
r  = requests.get(url=url, timeout=timeout)
content = r.text
```
when I comment out the second line this issue does not occur ... am I using the library fundamentally wrong or could this actually be a bug?

**Comment by Lukasa** [comment] 2017-07-12 15:35
What are you doing with the content? What's the rate of memory growth? Can you try following [this blog post](http://tech.labs.oliverwyman.com/blog/2008/11/14/tracing-python-memory-leaks/) to gather data about *what* objects are being retained, ideally after your memory has grown very substantially (e.g. to more than 10 times the initial process memory size).

**Comment by sigmavirus24** [comment] 2017-07-12 15:40
Also, I have a hunch, so humor my following question: Does the server provide a charset/character encoding? If not, does the leak persist if you do `content = r.content`?

@Lukasa I wonder if there's a leak in chardet.

**Comment by Lukasa** [comment] 2017-07-12 15:41
Good hunch. Checking if the problem appears with a change of `text` to `content` would also work to isolate that.

**Comment by le1nux** [comment] 2017-07-12 15:57
@Lukasa 
> What are you doing with the content?

I store  _content_ in a queue and have a worker thread that dumps the data in a csv file. 
However I isolated the download workers and skipped the part of storing it in the queue. 
So basically all I do now is this (using multiple threads):
```
while True:
    r  = requests.get(url=url, timeout=timeout)
    content = r.text
```
If I delete the assignment to _content_ the memory does not grow anymore.
```
while True:
    r  = requests.get(url=url, timeout=timeout)
```
> What's the rate of memory growth?

The initial RAM usage is at about 100MB and grows to 2GB within ~24 hours.

@sigmavirus24 
> Does the server provide a charset/character encoding?

Good question. Since my URL list contains more than 100 servers I would have to check for each. 
Besides what exactly do you mean by "charset/character encoding". Are you referring to the HTTP response header's field _Content-Encoding_? 
 
> If not, does the leak happen if you do content = r.content?

I will give that a try.

**Comment by Lukasa** [comment] 2017-07-12 15:58
No, @sigmavirus24 is referring to having a `charset` parameter in the `content-type` header field.

**Comment by le1nux** [comment] 2017-07-12 16:27
Ah okay. I wrote a little script that prints the content-type field of all responses. 
Content types are:
```
Content-Type: text/xml
Content-Type: text/xml;charset=UTF-8
Content-Type: application/rss+xml;charset=UTF-8
```
Additionally, some of those servers don't even provide a Content-Type field.

**Comment by Lukasa** [comment] 2017-07-12 16:32
Ok, so the ones with no `content-type` and the ones with no `charset` are the ones we're interested in. Try changing `text` to `content` to see if it reproduces.

**Comment by le1nux** [comment] 2017-07-12 21:04
Alright, I compared both versions now:

| time in h   | content        | text |
| ------------- |-------------| -----|
| 00:00       | 0.9%| 1.0% |
| 00:30       | 1.3%|1.7% |
| 01:00       | 1.4% |2.1% |
| 01:30       | 1.4% | |
| 02:00       | 1.4% | 2.3%|
| 02:30       | 1.4% |2.3% |
| 03:00       | 1.4% |2.4% |
| 03:30       | 1.5% |2.4% |
| 04:00       | 1.5% | 2.4%|
|4:30| | 2.5%|
|...|||
|~6:00h|1.6%| |

In case you're interested in absolute values: my notebook has 10GB of RAM. 
It seems like RAM usage growing something like a root function. 
This behavior is equivalent to what I have encountered when using my crawler although there it's taking GBs of RAM. 

This what my requests test script looks like:
https://gist.github.com/le1nux/c94b3707f076edbd982299906737b1ca

**Comment by Lukasa** [comment] 2017-07-13 07:57
Ok, so the leaking does appear to occur more *slowly* when using `content`, but it is vaguely present. In both of these cases, though, this may not be a leak: given that the growth is asymptotic it may be a property of the Python allocator, which does not always return object memory to the OS. In this case the process with `content` is asymptotically growing to about 160MB: large, but not completely absurd, especially for large response bodies.

I think we need to see `objgraph` results from a long run to see how much data is actually floating around.

**Comment by le1nux** [comment] 2017-07-13 10:37
>  In this case the process with content is asymptotically growing to about 160MB: large, but not completely absurd, especially for large response bodies.

Well, I only requested XML data which is not really big. 

Character length:

|   max   |   min   |   avg   |   median   |
|-----------|---------|----------|----------------|
| 610869 | 876 | 51329 | 21592|

I will replace my URL list by URLs that direct to bigger websites and see if I can reproduce the huge RAM usage of my crawler.

**Comment by sigmavirus24** [comment] 2017-07-13 11:47
> it may be a property of the Python allocator, which does not always return object memory to the OS.

So actually, the last time I spent a few weeks trying to track down a memory leak in requests what I learned is that the Resident Size measure (RSS) is actually not the amount of memory *actively* used by your program but the maximum amount of memory it has allocated thus far. And if your OS doesn't need to reclaim any of that, that value can stay the same and generally does not shrink.

**Comment by cjerdonek** [comment] 2017-07-13 12:04
Not sure how relevant it is, but there was an interesting thread a month ago on Python-Dev about CPython's memory allocation approach, and some of its consequences. The thread starts here:
https://mail.python.org/pipermail/python-dev/2017-June/148105.html

**Comment by le1nux** [comment] 2017-07-13 15:51
@sigmavirus24 
Good point. However I'm still asking myself why my crawler (i.e. the requests library probably) allocates that amount of RAM in the first place.

**Comment by sigmavirus24** [comment] 2017-07-13 16:16
@le1nux btw, can you please fill out the template you had to delete to report this issue in the first place. We *did* have a leak a couple years back with the functional API you're using and without knowing what version you're on, I don't have a good way of telling you if that's the issue.

**Comment by sigmavirus24** [comment] 2017-07-29 10:59
Hey @le1nux I'm going to close this since the investigation has stalled and we don't really have any concrete things to chase down. We'll be happy to reopen it if you can bring us the details we need to continue the investigation. Cheers!

**Closed by sigmavirus24** 2017-07-29 10:59 UTC

**Comment by le1nux** [comment] 2017-07-29 21:39
Hey @sigmavirus24 I'm sorry for not having provided any further information, yet. At the moment I'm busy working on something else but I will get back to it in approx. two weeks. I will investigate that issue further and if it persists I will come back to you guys.

**Comment by malizhi** [comment] 2018-02-02 12:54
i also have this issue, there is my message

![default](https://user-images.githubusercontent.com/12585859/35734180-33143dd8-085b-11e8-82ce-e4bfe7575ffd.PNG)


[...], 'user-agent'], [...], None], [...], 'connection'], [...], 'accept-encoding'], [[...], [[...], [[...], [[...], [...], 'accept-encoding'], 'connection'], None], 'user-agent'], 'accept'], [[[[[[...], [...], None], [...], 'connection'], [...], 'accept-encoding'], [...], 'accept'], [[...], [[...], [[...], [[...], [...], 'accept'], 'accept-encoding'], 'connection'], None], 'user-agent'], [[...], [...], None], [[[[[[...], [...], 'connection'], [...], 'accept-encoding'], [...], 'accept'], [...], 'user-agent'], [[...], [[...], [[...], [[...], [...], 'user-agent'], 'accept'], 'accept-encoding'], 'connection'], None], [[[[[[...], [...], 'accept-encoding'], [...], 'accept'], [...], 'user-agent'], [...], None], [[...], [[...], [[...], [[...], [...], None], 'user-agent'], 'accept'], 'accept-encoding'], 'connection'], [[[[[[...], [...], 'accept'], [...], 'user-agent'], [...], None], [...], 'connection'], [[...], [[...], [[...], [[...], [...], 'connection'], None], 'user-agent'], 'accept'], 'accept-encoding'], [[[[[[...], [...], 'user-agent'], [...], None], [...], 'connection'], [...], 'accept-encoding'], [[...], [[...], [[...], [[...], [...], 'accept-encoding'], 'connection'], None], 'user-agent'], 'accept'], [[[[[[...], [...], None], [...], 'connection'], [...], 'accept-encoding'], [...], 'accept'], [[...], [[...], [[...], [[...], [...], 'accept'], 'accept-encoding'], 'connection'], None], 'user-agent'], [[...], [...], None], [[...], [...], None], [[...], [...], None], [[[[[[...], [...], 'connection'], [...], 'accept-encoding'], [...], 'accept'], [...], 'user-agent'], [[...], [[...], [[...], [[...], [...], 'user-agent'], 'accept'], 'accept-encoding'], 'connection'], None], [[[[[[...], [...], 'accept-encoding'], [...], 'accept'], [...], 'user-agent'], [...], None], [[...], [[...], [[...], [[...], [...], None], 'user-agent'], 'accept'], 'accept-encoding'], 'connection'], [[[[[[...], [...], 'accept'], [...], 'user-agent'], [...], None], [...], 'connection'], [[...], [[...], [[...], [[...], [...], 'connection'], None], 'user-agent'], 'accept'], 'accept-encoding'], [[[[[[...] [[...], [[...], [[...], [[...], [[...], [[...], [...], 'content-type'], 'date'], 'server'], None], 'content-encoding'], 'set-cookie'], 'pragma'], 'cache-control'], 'connection'], 'transfer-encoding'], 'last-modified'], [[[[[[[[[[[[...], [...], 'connection'], [...], 'cache-control'], [...], 'pragma'], [...], 'set-cookie'], [...], 'content-encoding'], [...], None], [...], 'server'], [...], 'date'], [...], 'content-type'], [...], 'last-modified'], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [...], 'last-modified'], 'content-type'], 'date'], 'server'], None], 'content-encoding'], 'set-cookie'], 'pragma'], 'cache-control'], 'connection'], 'transfer-encoding'], [[[[[[[[[[[[...], [...], 'cache-control'], [...], 'pragma'], [...], 'set-cookie'], [...], 'content-encoding'], [...], None], [...], 'server'], [...], 'date'], [...], 'content-type'], [...], 'last-modified'], [...], 'transfer-encoding'], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [...], 'transfer-encoding'], 'last-modified'], 'content-type'], 'date'], 'server'], None], 'content-encoding'], 'set-cookie'], 'pragma'], 'cache-control'], 'connection'], [[[[[[[[[[[[...], [...], 'pragma'], [...], 'set-cookie'], [...], 'content-encoding'], [...], None], [...], 'server'], [...], 'date'], [...], 'content-type'], [...], 'last-modified'], [...], 'transfer-encoding'], [...], 'connection'], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [...], 'connection'], 'transfer-encoding'], 'last-modified'], 'content-type'], 'date'], 'server'], None], 'content-encoding'], 'set-cookie'], 'pragma'], 'cache-control'], [[[[[[[[[[[[...], [...], 'set-cookie'], [...], 'content-encoding'], [...], None], [...], 'server'], [...], 'date'], [...], 'content-type'], [...], 'last-modified'], [...], 'transfer-encoding'], [...], 'connection'], [...], 'cache-control'], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [[...], [...], 'cache-control'], 'connection'], 'transfer-encoding'], 'last-modified'], 'content-type'], 'date'], 'server'], None], 'content-encoding'], 'set-cookie'], 'pragma'], [[[[[[[[[[[[...], [...]

**Comment by walterwang** [comment] 2018-08-06 05:26
I have a similar issue where additional objects are created everytime r=requests.get() is called and r.content is retrieved in multithreaded program
                       <class 'str |           4 |    275     B
  <class 'urllib.parse.SplitResult |           1 |     88     B

**Comment by kfirfer** [comment] 2019-01-09 14:08
Using python 2.7.15 and requests 2.21.0
And I encountering the exact same memory leak.

**Comment by le1nux** [comment] 2019-01-15 22:31
Since this issue seems to persist for others, I set up my old crawler again and updated to the latest requests library version (2.21.0). I ran it for a couple of hours and the memory keeps still increasing. In my opinion my light-wight rss-feed-crawler might be an "easy" starting point to track it down? 

https://github.com/le1nux/crawly

In any case, I will be happy to assist tracking down this possible memory leak.

**Comment by BarryThrill** [comment] 2019-05-03 12:26
Python 3.7.2 and requests 2.21.0
And I also have the exact same memory leak.

**Comment by tallona** [comment] 2019-09-27 20:48
Having the same issue. I have a simple script that spawns a thread, this thread calls a function that runs on a while loop, this loop queries an API to check a status value and then sleeps for 10 seconds and then the loop will run again until the script is stopped.

When using the `request.get` function I can see the memory usage slowly creeping up via task manager by watching the spawned process.

But if I remove the `request.get` call from the loop or use `urllib3` directly to make the get request, there is very little if any creep of the memory usage.

I've watched this over a two hour period in both cases and when using `requests.get` the memory usage is at 1GB+ after two hours where as when using `urllib3` the memory usage is at approx. 20mb after two hours.

Any chance it can be re-opened, I can supply a simple script if needs be.

Python 3.7.4 and requests 2.22.0

**Comment by far-rainbow** [comment] 2019-12-09 09:54
09/12/2019
Windows-7 python38 requests 2.22.0 -- the same leakage found while on threadpool execution

**Comment by supersciencegrl** [comment] 2020-02-27 15:54
27 Dec 2020
Think I've found the same: Python 3.7, requests 2.22.0.

**Comment by John9570** [comment] 2020-03-21 22:12
I'm also seeing this exact same memory leak - Python 3.6.9, requests 2.23.0. Has anyone found any work arounds?
