### ISSUE TITLE
`requests.utils.guess_json_utf` breaks on Python 3

### ISSUE THREAD

**Issue by annakovale** [requests/requests#4880] opened 2018-11-26 21:38 UTC
Unable to use `Response.json()`. I notice `requests.utils.guess_json_utf` expects type str but then breaks at `sample.count(_null)`, understandably because `<str>.count(<bytes)` is not valid - [see the function here](https://github.com/requests/requests/blob/57d7284c1a245cf9fbcecb594f50471d86e879f7/requests/utils.py#L851-L886).

## Expected Result
```In [10]: from requests.models import Response

In [11]: response_dict = {'foo':'bar'}

In [12]: response = Response()

In [13]: response.status_code = 200

In [14]: response._content = json.dumps(response_dict)

In [15]: response.json()
'{'foo': 'bar'}'
```
## Actual Result
```
In [10]: from requests.models import Response

In [11]: response_dict = {'foo':'bar'}

In [12]: response = Response()

In [13]: response.status_code = 200

In [14]: response._content = json.dumps(response_dict)

In [15]: response.json()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-670418389d1b> in <module>()
----> 1 response.json()

/data/virtualenv/py3default/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    882             # decoding fails, fall back to `self.text` (using chardet to make
    883             # a best guess).
--> 884             encoding = guess_json_utf(self.content)
    885             if encoding is not None:
    886                 try:

/data/virtualenv/py3default/lib/python3.6/site-packages/requests/utils.py in guess_json_utf(data)
    868     if sample[:2] in (codecs.BOM_UTF16_LE, codecs.BOM_UTF16_BE):
    869         return 'utf-16'     # BOM included
--> 870     nullcount = sample.count(_null)
    871     if nullcount == 0:
    872         return 'utf-8'

TypeError: must be str, not bytes
```

## Reproduction Steps
Follow the steps in Actual Result

## System Information
```
(py3default) deploy@lemon:/data/shared/buffet/bokchoy/tests$ python -m requests.help
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.3.1"
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.6.6"
  },
  "platform": {
    "release": "4.4.0-51-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1010009f",
    "version": "18.0.0"
  },
  "requests": {
    "version": "2.19.1"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.23"
  },
  "using_pyopenssl": true
}
(py3default) deploy@lemon:/data/shared/buffet/bokchoy/tests$ python --version
Python 3.6.6
```

Possibly related to: https://github.com/requests/requests/issues/4879

**Comment by nateprewitt** [comment] 2018-11-26 21:48
Yep, this is a dupe of #4879. We’ll track there.

**Closed by nateprewitt** 2018-11-26 21:48 UTC
