### ISSUE TITLE
response.text is returning with header values.

### ISSUE THREAD

**Issue by selvaraju** [requests/requests#4588] opened 2018-04-13 04:47 UTC
Summary.
response.text is returning with header values.
## Expected Result
We are expecting only response content. but getting with header as well. Could you please help us to solve this issue ?
response.text  => {"@odata.context":"/redfish/v1/$metadata#ServiceRoot.ServiceRoot"}

## Actual Result
Getting response header with response.text like below
HTTP/1.1 200 OK
Content-Length: 807
OData-Version: 4.0
Content-Type: application/json
Date: Fri, 13 Apr 2018 04:38:07 GMT

{"@odata.context":"/redfish/v1/$metadata#ServiceRoot.ServiceRoot"}

## Reproduction Steps

```python
import requests

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "1.7.1"
  },
  "idna": {
    "version": "2.6"
  },
  "implementation": {
    "name": "CPython",
    "version": "2.7.12"
  },
  "platform": {
    "release": "4.4.0-93-generic",
    "system": "Linux"
  },
  "pyOpenSSL": {
    "openssl_version": "1000207f",
    "version": "16.2.0"
  },
  "requests": {
    "version": "2.18.4"
  },
  "system_ssl": {
    "version": "1000207f"
  },
  "urllib3": {
    "version": "1.22"
  },
  "using_pyopenssl": true
}
```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment] 2018-04-13 05:08
Hi @selvaraju, we don’t modify the body so it’s unlikely Requests is doing anything other than returning what the server sent.

We’ll need you to provide a reproduction script in order to investigate. Until then, I don’t know if there’s anything we can do here.

**Comment by nateprewitt** [comment] 2018-04-21 20:53
Hi @selvaraju, since this hasn't received a response, I'm going to close this out for now. Please feel free to reopen when you have a reproduction that shows the issue isn't related to the server you're connecting to. Thanks!

**Closed by nateprewitt** 2018-04-21 20:53 UTC
Labels: Needs More Information, Propose Close

**Comment by selvaraju** [comment] 2018-04-22 04:26
Thank you.  It was working fine python3. not in 2.7.it worked fine if we put some wait before calling request api
