### ISSUE TITLE
SSLError propagets urllib3 SSLError exception object as message

### ISSUE THREAD

**Issue by NikosVlagoidis** [requests/requests#4783] opened 2018-09-11 14:21 UTC
Summary.
On adapter.py [link](https://github.com/requests/requests/blob/8472dbd13408e35611a38d58f32eb531ce0ffe1e/requests/adapters.py#L524) we pass as the first parameter of the error an SSLError exception object. this has a result if you catch the error e.message is an object and not a string. Is this intented?

Maybe we need to pass 

```python
        except (_SSLError, _HTTPError) as e:
            if isinstance(e, _SSLError):
                # This branch is for urllib3 versions earlier than v1.22
                raise SSLError(e.message, request=request)
```

## Expected Result

```
from requests.exceptions import SSLError
from urllib3.exceptions import SSLError as _SSLError

a = SSLError(_SSLError, request="TEST")

print a.message


```

What you expected.

> "An SSL error occured"

## Actual Result

What happened instead.

> <class 'urllib3.exceptions.SSLError'>

## Reproduction Steps

```python
import requests
from requests.exceptions import SSLError
from urllib3.exceptions import SSLError as _SSLError

a = SSLError(_SSLError, request="TEST")

print a.message

```

## System Information

    $ python -m requests.help

```
{
  "chardet": {
    "version": "3.0.4"
  }, 
  "cryptography": {
    "version": "2.2.2"
  }, 
  "idna": {
    "version": "2.6"
  }, 
  "implementation": {
    "name": "CPython", 
    "version": "2.7.12"
  }, 
  "platform": {
    "release": "4.15.0-33-generic", 
    "system": "Linux"
  }, 
  "pyOpenSSL": {
    "openssl_version": "1010008f", 
    "version": "18.0.0"
  }, 
  "requests": {
    "version": "2.18.4"
  }, 
  "system_ssl": {
    "version": "1000207f"
  }, 
  "urllib3": {
    "version": "1.22"
  }, 
  "using_pyopenssl": true
}

```

This command is only available on Requests v2.16.4 and greater. Otherwise,
please provide some basic information about your system (Python version,
operating system, &c).

**Comment by nateprewitt** [comment] 2018-10-01 03:28
Hi @NikosVlagoidis, I'm a little confused about what we're expecting here. All of our wrapped exceptions should return an instantiation of the exception that we're wrapped which is represented by the `e` variable in the code your referenced. When that exception is returned, you should be able to call the `message` attribute on it and get what you want.

The reproduction code you've provided is wrapping an exception with the SSLError **class** rather than an SSLError **object** instantiation. I think we'd expect the output to be the class reference at that point which matches your observed behaviour.

I'm going to close this out for now since it doesn't seem there's an issue here. If you have more information, please feel free to provide it hear and reopen the issue. Thanks!

**Closed by nateprewitt** 2018-10-01 03:28 UTC
